migrate from cJSON to zcbor
golioth/golioth-firmware-sdk pull request #119
Opened 2023-06-13 13:56 UTC by mniestroj

~Depends on: #123~
~Depends on: #124~
Depends on: #126

TODO:
- [x] convert unit tests from cJSON to zcbor

2023-07-05 18:33 UTC, mniestroj commented
Unit tests of RPC need to be rewritten, but other than that, this PR is ready to be reviewed.

2023-07-10 20:21 UTC, sam-golioth requested changes

2023-07-11 12:40 UTC, mniestroj commented on port/esp_idf/components/golioth_sdk/CMakeLists.txt
> +        "${sdk_src}/zcbor_utils.c"
Moved to the commit which introduces this file.

2023-07-11 12:40 UTC, mniestroj commented on src/zcbor_utils.h
> +int zcbor_map_decode(zcbor_state_t* zsd, struct zcbor_map_entry* entries, size_t num_entries);
Sure, added doxygen comments.

2023-07-11 12:41 UTC, mniestroj commented on src/zcbor_utils.h
> +    return false;
Good call, simplified that function by removing `else` case.

2023-07-11 22:00 UTC, sam-golioth approved these changes
The RPC tests are in the remote shell commit, but other than that looks great!

2023-07-12 08:13 UTC, mniestroj commented
> The RPC tests are in the remote shell commit, but other than that looks great!

I've squashed those two, as `remote_shell` uses `rpc`, so both need to be changed at the same time.

2023-07-12 08:38 UTC, merged