use python virtual environment for HIL tests
golioth/golioth-firmware-sdk pull request #232
Opened 2023-11-10 23:16 UTC by szczys

Use a virtual environment to ensure that python packages installed on the system don't interfere with those installed by the test.

2023-11-16 21:15 UTC, sam-golioth requested changes
Using `venv` isn't necessarily bad, but it doesn't provide the same kind of isolation that Docker does, and it doesn't help us distribute non-python tools to the runners in a consistent way (e.g. JLink).

Dan and Jon spent some time debugging environment issues with GitHub and Docker, and I believe that a similar fix will allow us to Docker on the runners, which would remove the need for `venv`.

See: https://github.com/golioth/fw-oci-images/pull/14

2023-11-21 11:25 UTC, mniestroj commented
I think that using venv makes sense regardless of using Docker or not. pip package manager has recently enforced a policy (or at least I noticed it on Arch Linux an Debian 12) that prevents installing Python packages in system directories, which makes venv always required. Maybe used Ubuntu Docker image does not have that yet as requirement, but still, using venv won't hurt anyway. The idea behind this policy of using venv for pip installed packages is to split distribution Python packages from pip, since those are maintained in separate way and this was common source of conflicts.

So overall, I am lean towards merging this PR.

2023-11-21 11:25 UTC, mniestroj approved these changes

2023-11-21 11:31 UTC, hasheddan reviewed
Chatted with @szczys about this yesterday -- given that we are using the dependencies in every run here, it makes sense to run in a container image where they are already installed. If we move that direction, we can start venv as part of entrypoint on container startup. Anyone using the image, such as this workflow, shouldn't need to do any additional setup prior to invoking the tests 👍🏻

2023-11-29 20:44 UTC, closed without merging