Szczys/blocksize server suggests
golioth/golioth-firmware-sdk pull request #570
Opened 2024-09-03 18:39 UTC by szczys

2024-09-20 17:58 UTC, sam-golioth requested changes

2024-09-20 17:58 UTC, sam-golioth commented on src/coap_blockwise.c
> +    /* Subtract 1 to indicate the block we just sent; inc happens after return */
This function shouldn't assume what the caller will or will not do. Instead, it should describe what it does, and the caller can act accordingly.

2024-09-20 17:58 UTC, sam-golioth commented on src/zephyr_coap_req.c
> +                golioth_coap_request_msg_t *rmsg = req->user_data;
We should not be modifying user data inside this function. The expectation of the caller is that user data is passed unmodified.

Rather trying to overload the user_data with more than one purpose, we should additional arguments to the functions in the call chain so we can pass back the negotiated block size explicitly.

2024-09-26 02:37 UTC, szczys commented
In the latest updates I used a private set_block callback typedef in coap_client.h.

I think we should also move the get_block callback out of include/golioth/client.h and into the coap_client.h as it is only referenced by internal functions not available in our api.

https://github.com/golioth/golioth-firmware-sdk/blob/2f61304dffaf9d1b5da5a0d22d657440c4b75f38/include/golioth/client.h#L162-L181

2024-10-03 18:52 UTC, merged