coap_client_zephyr: ensure keepalive timer reset on observation
golioth/golioth-firmware-sdk pull request #672
Opened 2024-11-14 00:56 UTC by sam-golioth

Ensure that we reset the keepalive timer when we receive an observation response.

2024-11-15 15:13 UTC, szczys requested changes

2024-11-15 15:13 UTC, szczys commented on src/coap_client_zephyr.c
> +            break;
If we break here, the request memory will be freed at the bottom of the function and will cause a use after free error when trying to reestablish observations after a client start/stop. I tested this with a mimxrt1024_evk on the RPC integration test and received an MPU fault.

However, I made the same change (not for the same reason) in the callbacks on cancellation PR: https://github.com/golioth/golioth-firmware-sdk/pull/669/commits/1f7fbfb2d9bf3f78d624e1f0654e5e3f3f228fdf

The commit before that change adds a conditional check just before the free operation that returns if the type is an observation:
https://github.com/golioth/golioth-firmware-sdk/pull/669/commits/f671be0b82eab926ffa0bcf2e90b1d45b08460eb#diff-1478f24ca0f9d927604108f856f882c69c95561f408c7c9a26ac1d823b8db085R314

2024-11-15 17:56 UTC, szczys commented
Should we also reset the keepalive for EMPTY and OBSERVE_RELEASE? 

https://github.com/golioth/golioth-firmware-sdk/blob/5ece8c9dad89006dbb94e529c27d10e805ed6df4/src/coap_client_zephyr.c#L262

2024-11-20 19:09 UTC, sam-golioth commented on src/coap_client_zephyr.c
> +            break;
Great catch! I agree your changes address this better, will close this PR.

2024-11-20 19:09 UTC, closed without merging