release v0.16.0
golioth/golioth-firmware-sdk pull request #691
Opened 2024-11-22 20:48 UTC by szczys

see CHANGELOG for details.

2024-11-22 22:03 UTC, sam-golioth requested changes
We also need to update the tag references in git clone, west init, and west manifest instructions in `README.me` and `examples/zephyr/README.md`.

2024-11-22 22:03 UTC, sam-golioth commented on CHANGELOG.md
> +- NCS port updated to NCS v2.8
I think "Improved OTA stability" is also a highlight

2024-11-24 17:17 UTC, szczys commented on CHANGELOG.md
> +  demonstrated in that sample.
Add a known issue about the esp32 certificates build

2024-11-25 18:06 UTC, sam-golioth approved these changes

2024-11-25 20:21 UTC, merged